services:
    api:
        build: .
        container_name: v34_fastapi
        ports:
            - "8000:8000"
        env_file:
            - .env
        depends_on:
            - db
        restart: always

    db:
        image: pgvector/pgvector:pg17
        container_name: v34_postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always
volumes:
    postgres_data:
