[tool.black]
line-length = 79 
target-version = ["py310"]  
skip-string-normalization = false
skip-magic-trailing-comma = false

[tool.isort]
profile = "black" 
line_length = 79
known_first_party = ["your_project"] 
force_sort_within_sections = true
combine_as_imports = true
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
lines_between_types = 1  