"""Add role enum to users

Revision ID: 14328d908c1e
Revises: 3d8bcb51077e
Create Date: 2025-07-22 20:47:11.086468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14328d908c1e"
down_revision: Union[str, None] = "3d8bcb51077e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = sa.Enum("ADMIN", "USER", name="userrole")


def upgrade() -> None:
    """Upgrade schema."""
    # Create the userrole type
    user_role_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "role",
            user_role_enum,
            nullable=False,
            server_default="USER",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role", server_default=None)
    user_role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
