"""update search query

Revision ID: 164947189b2b
Revises: 6032a65b9551
Create Date: 2025-06-17 15:49:00.923792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164947189b2b'
down_revision: Union[str, None] = '6032a65b9551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('search_query_key'), 'search', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('search_query_key'), 'search', ['query'])
    # ### end Alembic commands ###
