"""remove index from search query

Revision ID: 6032a65b9551
Revises: 7443b716174d
Create Date: 2025-06-17 15:41:10.111669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6032a65b9551'
down_revision: Union[str, None] = '7443b716174d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_query'), table_name='search')
    op.create_unique_constraint(None, 'search', ['query'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search', type_='unique')
    op.create_index(op.f('ix_search_query'), 'search', ['query'], unique=True)
    # ### end Alembic commands ###
